version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
  redis:
    image: redislabs/redismod:latest
    command: --loadmodule /usr/lib/redis/modules/redisearch.so --loadmodule /usr/lib/redis/modules/redisgraph.so --loadmodule /usr/lib/redis/modules/rejson.so --dir /data
#   ports:
#     - 6379:6379
    volumes:
      - ./redis-data:/data
  frontend:
    image: redis21_frontend
    volumes:
      - ./frontend:/app
  backend:
    image: redis21_backend
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000 --root-path /api --reload
    depends_on:
      - redis
    environment:
      - HOST=http://127.0.0.1:8000
    volumes:
      - ./backend:/app
